type Coffee {
  amount: String!
  notes: String
  person: Person
}

type Person {
  name: String!
  slug: String!
  age: Int!
  avatar: String
  coffees: [Coffee] @relation
}

type Query {
  person: [Person]
  getPersonBySlug(slug: String!): Person!
}
